export interface Infracao {
  resumo: string
  descricao_completa: string
  fundamento_legal: string
  natureza_multa?: string
  valor_minimo?: number
  valor_maximo?: number
  valor_por_unidade?: number | null
  unidade_de_medida?: string | null
  criterios_aplicacao?: string
  observacoes?: string
  _categoria?: string
  _tipo_multa_computado?: "aberta" | "fechada"
}

interface InfracaoBloco {
  tipo_infracao: string
  infracoes: Infracao[]
}

// Função para detectar tipo de multa
function detectTipoMulta(item: Infracao): "aberta" | "fechada" {
  try {
    const txt = `${item.descricao_completa || ""} ${item.resumo || ""} ${item.fundamento_legal || ""}`.replace(
      /\s+/g,
      " ",
    )

    // 1) Padrão textual "R$ X a R$ Y" => intervalo => aberta
    const hasRangeText = /R\$\s*\d{1,3}(\.\d{3})*,\d{2}\s*(?:a|até)\s*R\$\s*\d{1,3}(\.\d{3})*,\d{2}/i.test(txt)

    // 2) Intervalos por campos: valor_minimo/valor_maximo diferentes e presentes => aberta
    const vmin = (item.valor_minimo || "").toString().trim()
    const vmax = (item.valor_maximo || "").toString().trim()
    const hasIntervalFields = vmin && vmax && vmin !== vmax

    // 3) Multa fechada geralmente tem valor_por_unidade e/ou unidade_de_medida definidos
    const hasUnitFields = !!item.valor_por_unidade || !!item.unidade_de_medida

    // 4) Campo natureza_multa se existir, usamos apenas como fallback
    const natureField = (item.natureza_multa || "").toString().toLowerCase()

    // Regras de decisão
    if (hasRangeText || hasIntervalFields) return "aberta"
    if (hasUnitFields) return "fechada"
    if (natureField === "aberta" || natureField === "fechada") return natureField as "aberta" | "fechada"

    // Heurística adicional
    const unitHints =
      /(por\s+(quilo|kg|hectare|árvore|árvores|unidade|indivíduo|exemplar|m³|metro\s*cúbico|m2|m²|m3|litro|litros|peça|peças|fração))/i
    if (unitHints.test(txt)) return "fechada"

    return "aberta"
  } catch {
    return "aberta"
  }
}

// Dados das infrações extraídos automaticamente
const rawData: InfracaoBloco[] = [
  {
    "tipo_infracao": "ATIVIDADE SEM LICENÇA",
    "infracoes": [
      {
        "resumo": "ATIVIDADE SEM LICENÇA/DESCUMPRIMENTO DE CONDICIONANTES",
        "descricao_completa": "Construir, reformar, ampliar, instalar ou fazer funcionar estabelecimentos, atividades, obras ou serviços utilizadores de recursos ambientais, considerados efetiva ou potencialmente poluidores, sem licença ou autorização dos órgãos ambientais competentes, em desacordo com a licença obtida ou contrariando as normas legais e regulamentos pertinentes",
        "fundamento_legal": "Art. 82, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 500,
        "valor_maximo": 10000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Construir, reformar, amplira, instalar ou faerz funcionar estabelecimento, obra ou serviço sujeito a licenciamento ambiental localizado em unidade de conservação ou em sua zona de amortecimento, ou em áreas de proteção de mananciais legalmente estabelecidas, sem anuência do respectivo órgão gestor",
        "descricao_completa": "constrói, reforma, amplia, instala ou faz funcionar estabelecimento, obra ou serviço sujeito a licenciamento ambiental localizado em unidade de conservação ou em sua zona de amortecimento, ou em áreas de proteção de mananciais legalmente estabelecidas, sem anuência do respectivo órgão gestor",
        "fundamento_legal": "Art. 82, I, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 500,
        "valor_maximo": 10000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      }
    ]
  },
  {
    "tipo_infracao": "DAS INFRAÇÕES ADMINISTRATIVAS CONTRA A ADMINISTRAÇÃO AMBIENTAL",
    "infracoes": [
      {
        "resumo": "Obstar ou dificultar a ação do Poder Público no exercício de atividades de fiscalização ambiental",
        "descricao_completa": "Obstar ou dificultar a ação do Poder Público no exercício de atividades de fiscalização ambiental",
        "fundamento_legal": "Art. 90, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 500,
        "valor_maximo": 100000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Obstar ou dificultar a ação do órgão ambiental",
        "descricao_completa": "Obstar ou dificultar a ação do órgão ambiental, ou de terceiro por ele encarregado, na coleta de dados para a execução de georreferenciamento de imóveis rurais para fins de fiscalização",
        "fundamento_legal": "Art. 91, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 100,
        "valor_maximo": 300,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Descumprir embargo de obra ou atividade",
        "descricao_completa": "Descumprir embargo de obra ou atividade e suas respectivas áreas",
        "fundamento_legal": "Art. 92, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 10000,
        "valor_maximo": 10000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Deixar de atender a exigências legais ou regulamentares",
        "descricao_completa": "Deixar de atender a exigências legais ou regulamentares quando devidamente notificado pela Autoridade competente no prazo concedido, visando à regularização, correção ou adoção de medidas de controle para cessar a degradação ambiental",
        "fundamento_legal": "Art. 93, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 1000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Deixar de apresentar relatórios ou informações ambientais nos prazos exigidos pela legislação",
        "descricao_completa": "Deixar de apresentar relatórios ou informações ambientais nos prazos exigidos pela legislação ou, quando aplicável, naquele determinado pela Autoridade Ambiental",
        "fundamento_legal": "Art. 94, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 1000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Elaborar ou apresentar informação, estudo, laudo ou relatório ambiental total ou parcialmente falso, enganoso ou omisso",
        "descricao_completa": "Elaborar ou apresentar informação, estudo, laudo ou relatório ambiental total ou parcialmente falso, enganoso ou omisso, seja nos sistemas oficiais de controle, seja no licenciamento, na concessão florestal ou em qualquer outro procedimento administrativo ambiental",
        "fundamento_legal": "Art. 95, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1500,
        "valor_maximo": 1000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Deixar de cumprir compensação ambiental determinada por lei",
        "descricao_completa": "Deixar de cumprir compensação ambiental determinada por lei, na forma e no prazo exigidos pela Autoridade Ambiental",
        "fundamento_legal": "Art. 96, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 10000,
        "valor_maximo": 1000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Comprar, vender, intermediar, utilizar, produzir, armazenar, transportar, importar, exportar, financiar e fomentar produto, substância ou espécie animal ou vegetal sem autorização, licença ou permissão ambiental válida ou em desacordo com aquela concedida",
        "descricao_completa": "Comprar, vender, intermediar, utilizar, produzir, armazenar, transportar, importar, exportar, financiar e fomentar produto, substância ou espécie animal ou vegetal sem autorização, licença ou permissão ambiental válida ou em desacordo com aquela concedida",
        "fundamento_legal": "Art. 97, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 100,
        "valor_maximo": 1000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Deixar de reparar, compensar ou indenizar dano ambiental",
        "descricao_completa": "Deixar de reparar, compensar ou indenizar dano ambiental, na forma e no prazo exigidos pela autoridade competente, ou implementar prestação em desacordo com a definida",
        "fundamento_legal": "Art. 98, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 10000,
        "valor_maximo": 50000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      }
    ]
  },
  {
    "tipo_infracao": "DAS INFRAÇÕES COMETIDAS CONTRA AS NORMAS DE GESTÃO E UTILIZAÇÃO DE RECURSOS HÍDRICOS",
    "infracoes": [
      {
        "resumo": "Derivar ou utilizar recursos hídricos para qualquer finalidade, sem a respectiva outorga de direito de uso",
        "descricao_completa": "Derivar ou utilizar recursos hídricos para qualquer finalidade, sem a respectiva outorga de direito de uso",
        "fundamento_legal": "Art. 108, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 10000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Iniciar a implantação ou implantar empreendimento relacionado com a derivação ou a utilização de recursos hídricos, superficiais ou subterrâneos, que implique alterações no regime, quantidade ou qualidade dos mesmos, sem autorização dos órgãos ou entidades competentes",
        "descricao_completa": "Iniciar a implantação ou implantar empreendimento relacionado com a derivação ou a utilização de recursos hídricos, superficiais ou subterrâneos, que implique alterações no regime, quantidade ou qualidade dos mesmos, sem autorização dos órgãos ou entidades competentes",
        "fundamento_legal": "Art. 109, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 5000,
        "valor_maximo": 50000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Utilizar-se dos recursos hídricos ou executar obras ou serviços relacionados com os mesmos em desacordo com as condições estabelecidas na outorga",
        "descricao_completa": "Utilizar-se dos recursos hídricos ou executar obras ou serviços relacionados com os mesmos em desacordo com as condições estabelecidas na outorga",
        "fundamento_legal": "Art. 110, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 5000,
        "valor_maximo": 50000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Perfurar poços para extração de água subterrânea ou operá-los sem a devida autorização",
        "descricao_completa": "Perfurar poços para extração de água subterrânea ou operá-los sem a devida autorização",
        "fundamento_legal": "Art. 111, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 2000,
        "valor_maximo": 20000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Fraudar as medições dos volumes de água utilizados ou declarar valores diferentes dos medidos",
        "descricao_completa": "Fraudar as medições dos volumes de água utilizados ou declarar valores diferentes dos medidos",
        "fundamento_legal": "Art. 112, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 2000,
        "valor_maximo": 20000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Infringir normas estabelecidas em Lei, Decretos e regulamentos administrativos, compreendendo instruções e procedimentos fixados pelos órgãos ou entidades competentes",
        "descricao_completa": "Infringir normas estabelecidas em Lei, Decretos e regulamentos administrativos, compreendendo instruções e procedimentos fixados pelos órgãos ou entidades competentes",
        "fundamento_legal": "Art. 113, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 2000,
        "valor_maximo": 20000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Obstar ou dificultar a ação fiscalizadora das autoridades competentes, no exercício de suas funções",
        "descricao_completa": "Obstar ou dificultar a ação fiscalizadora das autoridades competentes, no exercício de suas funções",
        "fundamento_legal": "Art. 114, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 2000,
        "valor_maximo": 20000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Continuar a utilizar o recurso hídrico após o término do prazo estabelecido na outorga sem a prorrogação ou revalidação desta",
        "descricao_completa": "Continuar a utilizar o recurso hídrico após o término do prazo estabelecido na outorga sem a prorrogação ou revalidação desta",
        "fundamento_legal": "Art. 115, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 5000,
        "valor_maximo": 50000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Poluir ou degradar recursos hídricos, acima dos limites estabelecidos na legislação ambiental pertinente",
        "descricao_completa": "Poluir ou degradar recursos hídricos, acima dos limites estabelecidos na legislação ambiental pertinente",
        "fundamento_legal": "Art. 116, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 50000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Degradar ou impedir a regeneração de florestas e demais formas de vegetação permanente, adjacentes aos recursos hídricos, definidas no Código Florestal",
        "descricao_completa": "Degradar ou impedir a regeneração de florestas e demais formas de vegetação permanente, adjacentes aos recursos hídricos, definidas no Código Florestal",
        "fundamento_legal": "Art. 117, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 50000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Utilizar recurso hídrico de maneira prejudicial a direito de terceiros e à vazão mínima remanescente estabelecida",
        "descricao_completa": "Utilizar recurso hídrico de maneira prejudicial a direito de terceiros e à vazão mínima remanescente estabelecida",
        "fundamento_legal": "Art. 118, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 10000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Descumprir determinações normativas ou atos emanados das autoridades competentes visando a aplicação deste Decreto",
        "descricao_completa": "Descumprir determinações normativas ou atos emanados das autoridades competentes visando a aplicação deste Decreto",
        "fundamento_legal": "Art. 119, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 5000,
        "valor_maximo": 50000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      }
    ]
  },
  {
    "tipo_infracao": "DAS INFRAÇÕES COMETIDAS EXCLUSIVAMENTE EM UNIDADES DE CONSERVAÇÃO",
    "infracoes": [
      {
        "resumo": "Introduzir em unidade de conservação do Estado espécies alóctones",
        "descricao_completa": "Introduzir em unidade de conservação do Estado espécies alóctones",
        "fundamento_legal": "Art. 99, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 2000,
        "valor_maximo": 100000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Violar as limitações administrativas provisórias impostas às atividades efetiva ou potencialmente causadoras de degradação ambiental nas áreas delimitadas para realização de estudos com vistas à criação de unidade de conservação",
        "descricao_completa": "Violar as limitações administrativas provisórias impostas às atividades efetiva ou potencialmente causadoras de degradação ambiental nas áreas delimitadas para realização de estudos com vistas à criação de unidade de conservação",
        "fundamento_legal": "Art. 100, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1500,
        "valor_maximo": 1000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Realizar pesquisa científica, envolvendo ou não coleta de material biológico, em unidade de conservação estadual sem a devida autorização, quando esta for exigível",
        "descricao_completa": "Realizar pesquisa científica, envolvendo ou não coleta de material biológico, em unidade de conservação estadual sem a devida autorização, quando esta for exigível",
        "fundamento_legal": "Art. 101, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 500,
        "valor_maximo": 10000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Explorar ou fazer uso comercial de imagem de unidade de conservação sem autorização do órgão gestor da unidade ou em desacordo com a recebida",
        "descricao_completa": "Explorar ou fazer uso comercial de imagem de unidade de conservação sem autorização do órgão gestor da unidade ou em desacordo com a recebida. Parágrafo único. Excetuam-se do disposto neste artigo as áreas \nde proteção ambiental e reservas particulares do patrimônio natural.",
        "fundamento_legal": "Art. 102, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 5000,
        "valor_maximo": 2000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Realizar liberação planejada ou cultivo de organismos geneticamente modificados em áreas de proteção ambiental do Estado, ou zonas de amortecimento das demais categorias de unidades de conservação, em desacordo com o estabelecido em seus respectivos planos de manejo, regulamentos ou recomendações da Comissão Técnica Nacional de Biossegurança – CTNBio",
        "descricao_completa": "Realizar liberação planejada ou cultivo de organismos geneticamente modificados em áreas de proteção ambiental do Estado, ou zonas de amortecimento das demais categorias de unidades de conservação, em desacordo com o estabelecido em seus respectivos planos de manejo, regulamentos ou recomendações da Comissão Técnica Nacional de Biossegurança – CTNBio",
        "fundamento_legal": "Art. 103, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1500,
        "valor_maximo": 1000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Realizar quaisquer atividades ou adotar conduta em desacordo com os objetivos da unidade de conservação, o seu plano de manejo e regulamentos",
        "descricao_completa": "Realizar quaisquer atividades ou adotar conduta em desacordo com os objetivos da unidade de conservação, o seu plano de manejo e regulamentos",
        "fundamento_legal": "Art. 104, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 500,
        "valor_maximo": 10000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Causar dano à unidade de conservação",
        "descricao_completa": "Causar dano à unidade de conservação",
        "fundamento_legal": "Art. 105, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 200,
        "valor_maximo": 100000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Penetrar em unidade de conservação conduzindo substâncias ou instrumentos próprios para caça, pesca ou para exploração de produtos ou subprodutos florestais e minerais, sem licença da autoridade competente, quando esta for exigível",
        "descricao_completa": "Penetrar em unidade de conservação conduzindo substâncias ou instrumentos próprios para caça, pesca ou para exploração de produtos ou subprodutos florestais e minerais, sem licença da autoridade competente, quando esta for exigível",
        "fundamento_legal": "Art. 106, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 10000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "penetrar em unidade de conservação cuja visitação pública ou permanência sejam vedadas pelas normas aplicáveis ou ocorram em desacordo com a licença da autoridade competente",
        "descricao_completa": "penetrar em unidade de conservação cuja visitação pública ou permanência sejam vedadas pelas normas aplicáveis ou ocorram em desacordo com a licença da autoridade competente",
        "fundamento_legal": "Art. 106 PARÁGRAFO ÚNICO, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 10000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      }
    ]
  },
  {
    "tipo_infracao": "DAS INFRAÇÕES CONTRA O ORDENAMENTO URBANO E O PATRIMÔNIO CULTURAL",
    "infracoes": [
      {
        "resumo": "Destruir, inutilizar ou deteriorar bem especialmente protegido por lei, ato administrativo ou decisão judicial.",
        "descricao_completa": "Destruir, inutilizar ou deteriorar bem especialmente protegido por lei, ato administrativo ou decisão judicial.",
        "fundamento_legal": "Art. 86, I, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 10000,
        "valor_maximo": 500000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Destruir, inutilizar ou deteriorar arquivo, registro, museu, biblioteca, pinacoteca, instalação científica ou similar protegido por lei, ato administrativo ou decisão judicial",
        "descricao_completa": "Destruir, inutilizar ou deteriorar arquivo, registro, museu, biblioteca, pinacoteca, instalação científica ou similar protegido por lei, ato administrativo ou decisão judicial",
        "fundamento_legal": "Art. 86, II, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 10000,
        "valor_maximo": 500000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Alterar o aspecto ou estrutura de edificação ou local especialmente protegido por lei",
        "descricao_completa": "Alterar o aspecto ou estrutura de edificação ou local especialmente protegido por lei, ato administrativo ou decisão judicial, em razão de seu valor paisagístico, ecológico, turístico, artístico, histórico, cultural, religioso, arqueológico, etnográfico ou monumental, sem autorização da autoridade competente ou em desacordo com a concedida",
        "fundamento_legal": "Art. 87, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 10000,
        "valor_maximo": 200000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Promover construção em solo não edificável, ou no seu entorno, assim considerado em razão de seu valor paisagístico, ecológico, artístico, turístico, histórico, cultural, religioso, arqueológico, etnográfico ou monumental, sem autorização da autoridade competente ou em desacordo com a concedida",
        "descricao_completa": "Promover construção em solo não edificável, ou no seu entorno, assim considerado em razão de seu valor paisagístico, ecológico, artístico, turístico, histórico, cultural, religioso, arqueológico, etnográfico ou monumental, sem autorização da autoridade competente ou em desacordo com a concedida",
        "fundamento_legal": "Art. 88, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 10000,
        "valor_maximo": 100000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Pichar, grafitar ou por outro meio conspurcar edificação alheia ou monumento urbano",
        "descricao_completa": "Pichar, grafitar ou por outro meio conspurcar edificação alheia ou monumento urbano",
        "fundamento_legal": "Art. 89, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 50000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      }
    ]
  },
  {
    "tipo_infracao": "DESCUMPRIMENTO DE CONDICIONANTES",
    "infracoes": [
      {
        "resumo": "Descumprimento de condicionantes",
        "descricao_completa": "deixa de atender as condicionantes estabelecidas na licença ambiental.",
        "fundamento_legal": "Art. 82, II, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 500,
        "valor_maximo": 10000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      }
    ]
  },
  {
    "tipo_infracao": "DISCEMINAÇÃO DE DOENÇA/PRAGA/ESPÉCIES DANOSAS",
    "infracoes": [
      {
        "resumo": "Disseminar doença ou praga ou espécies que possam causar dano à fauna, à flora ou aos ecossistemas",
        "descricao_completa": "Disseminar doença ou praga ou espécies que possam causar dano à fauna, à flora ou aos ecossistemas",
        "fundamento_legal": "Art. 83, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 5000,
        "valor_maximo": 5000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      }
    ]
  },
  {
    "tipo_infracao": "FAUNA",
    "infracoes": [
      {
        "resumo": "Matar, perseguir, caçar, apanhar, coletar, utilizar espécimes da fauna silvestre, nativos ou em rota migratória,",
        "descricao_completa": "Matar, perseguir, caçar, apanhar, coletar, utilizar \nespécimes da fauna silvestre, nativos ou em rota migratória, sem a devida permissão, licença ou autorização da autoridade competente, ou em desacordo \ncom a obtida. Multa de:",
        "fundamento_legal": "Art. 40, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 500,
        "valor_maximo": 50000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "R$ 5.000,00 por indivíduo",
        "fixo": "R$ 5.000,00 por indivíduo"
      },
      {
        "resumo": "Introduzir espécime animal silvestre, nativo ou exótico, no Estado.",
        "descricao_completa": "Introduzir espécime animal silvestre, nativo ou exótico, \nno Estado, sem parecer técnico oficial favorável e licença expedida pela Autoridade competente, quando exigível:",
        "fundamento_legal": "Art. 41, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 2000,
        "valor_maximo": 50000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "R$ 2.000,00 com acrescimo de R$ 5.000,00 (cinco mil reais), por indivíduo de espécie constante de listas oficiais de fauna brasileira ameaçada de extinção, inclusive da CITES.",
        "fixo": "R$ 2.000,00 com acrescimo de R$ 5.000,00 (cinco mil reais), por indivíduo de espécie constante de listas oficiais de fauna brasileira ameaçada de extinção, inclusive da CITES."
      },
      {
        "resumo": "Exportar peles e couros de anfíbios e répteis em bruto, sem autorização da autoridade competente:",
        "descricao_completa": "Exportar peles e couros de anfíbios e répteis em bruto, sem autorização da autoridade competente:",
        "fundamento_legal": "Art. 42, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 2000,
        "valor_maximo": 50000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "R$ 2.000,00 com acrescimo de R$ 5.000,00 (cinco mil reais), por indivíduo de espécie constante de listas oficiais de fauna brasileira ameaçada de extinção, inclusive da CITES.",
        "fixo": "R$ 2.000,00 com acrescimo de R$ 5.000,00 (cinco mil reais), por indivíduo de espécie constante de listas oficiais de fauna brasileira ameaçada de extinção, inclusive da CITES."
      },
      {
        "resumo": "Praticar caça profissional:",
        "descricao_completa": "Praticar caça profissional:",
        "fundamento_legal": "Art. 43, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 5000,
        "valor_maximo": 50000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "R$ 5.000,00 (cinco mil reais), com acréscimo de R$ 10.000,00 (dez mil reais) por indivíduo de espécie constante de listas oficiais de fauna brasileira ameaçada de extinção, inclusive da CITES.",
        "fixo": "R$ 5.000,00 (cinco mil reais), com acréscimo de R$ 10.000,00 (dez mil reais) por indivíduo de espécie constante de listas oficiais de fauna brasileira ameaçada de extinção, inclusive da CITES."
      },
      {
        "resumo": "Comercializar produtos, instrumentos e objetos que impliquem a caça",
        "descricao_completa": "Comercializar produtos, instrumentos e objetos que impliquem a caça, perseguição, destruição ou apanha de espécimes da fauna \nsilvestre:",
        "fundamento_legal": "Art. 44, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 50000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "R$ 1.000,00 (mil reais), com acréscimo de R$ 200,00 (duzentos reais), por unidade excedente.",
        "fixo": "R$ 1.000,00 (mil reais), com acréscimo de R$ 200,00 (duzentos reais), por unidade excedente."
      },
      {
        "resumo": "Praticar ato de abuso, maus-tratos, ferir ou mutilar animais",
        "descricao_completa": "Praticar ato de abuso, maus-tratos, ferir ou mutilar \nanimais silvestres, domésticos ou domesticados, nativos ou exóticos:",
        "fundamento_legal": "Art. 45, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 500,
        "valor_maximo": 3000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Deixarem, o jardim zoológico e os criadouros \nautorizados, de ter o livro de registro do acervo faunístico ou mantê-lo de \nforma irregular:",
        "descricao_completa": "Deixarem, o jardim zoológico e os criadouros \nautorizados, de ter o livro de registro do acervo faunístico ou mantê-lo de forma irregular:",
        "fundamento_legal": "Art. 46, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 500,
        "valor_maximo": 5000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Deixar, o comerciante, de apresentar declaração de estoque e valores oriundos de comércio de animais silvestres:",
        "descricao_completa": "Deixar, o comerciante, de apresentar declaração de \nestoque e valores oriundos de comércio de animais silvestres:",
        "fundamento_legal": "Art. 47, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 200,
        "valor_maximo": 10000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "nan",
        "fixo": "nan"
      },
      {
        "resumo": "Explorar ou fazer uso comercial de imagem de animal silvestre mantido irregularmente em cativeiro ou em situação de abuso ou \nmaus-tratos:",
        "descricao_completa": "Explorar ou fazer uso comercial de imagem de animal \nsilvestre mantido irregularmente em cativeiro ou em situação de abuso ou maus-tratos:",
        "fundamento_legal": "Art. 48, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 5000,
        "valor_maximo": 500000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "nan",
        "fixo": "nan"
      },
      {
        "resumo": "Causar degradação em viveiros, açudes ou estação de aquicultura de domínio público:",
        "descricao_completa": "Causar degradação em viveiros, açudes ou estação de aquicultura de domínio público:",
        "fundamento_legal": "Art. 49, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 5000,
        "valor_maximo": 500000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "nan",
        "fixo": "nan"
      },
      {
        "resumo": "Pescar em período ou local no qual a pesca seja proibida:",
        "descricao_completa": "Pescar em período ou local no qual a pesca seja \nproibida:",
        "fundamento_legal": "Art. 50, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 700,
        "valor_maximo": 100000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "acréscimo de R$ 20,00 (vinte reais) por quilo ou fração do produto da pescaria ou por espécime, quando se tratar de produto de pesca para uso ornamental.",
        "fixo": "acréscimo de R$ 20,00 (vinte reais) por quilo ou fração do produto da pescaria ou por espécime, quando se tratar de produto de pesca para uso ornamental."
      },
      {
        "resumo": "Pescar mediante a utilização de explosivos ou \nsubstâncias tóxicas",
        "descricao_completa": "Pescar mediante a utilização de explosivos ou \nsubstâncias que, em contato com a água, produzam efeitos semelhantes, ou  substâncias tóxicas, ou ainda, por outro meio proibido pela autoridade  competente:",
        "fundamento_legal": "Art. 51, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 700,
        "valor_maximo": 100000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "acréscimo de R$ 20,00 (vinte reais) por quilo ou fração do produto da pescaria.",
        "fixo": "acréscimo de R$ 20,00 (vinte reais) por quilo ou fração do produto da pescaria."
      },
      {
        "resumo": "Exercer a pesca sem prévio cadastro",
        "descricao_completa": "Exercer a pesca sem prévio cadastro, inscrição, \nautorização, licença, permissão ou registro do órgão competente, ou em desacordo com o obtido:",
        "fundamento_legal": "Art. 52, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 300,
        "valor_maximo": 10000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "acréscimo de R$ 20,00 (vinte reais) por quilo ou fração do produto da pesca ou por espécime, quando se tratar de produto de pesca para ornamentação.",
        "fixo": "acréscimo de R$ 20,00 (vinte reais) por quilo ou fração do produto da pesca ou por espécime, quando se tratar de produto de pesca para ornamentação."
      },
      {
        "resumo": "Deixarem, os comandantes de embarcações destinadas à pesca, de preencher e entregar, ao fim de cada viagem ou semanalmente, os  mapas fornecidos pelo órgão competente",
        "descricao_completa": "Deixarem, os comandantes de embarcações destinadas à pesca, de preencher e entregar, ao fim de cada viagem ou semanalmente, os  mapas fornecidos pelo órgão competente:",
        "fundamento_legal": "Art. 54, Decreto nº 7.315/2025",
        "natureza_multa": "FECHADA",
        "valor_minimo": 1000,
        "valor_maximo": 1000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: NÃO SE APLICA | Atenuantes: NÃO SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": ""
      }
    ]
  },
  {
    "tipo_infracao": "FAUNA/FLORA",
    "infracoes": [
      {
        "resumo": "Adquirir, intermediar, transportar ou comercializar produto ou subproduto de origem animal ou vegetal produzido sobre área objeto de embargo",
        "descricao_completa": "Adquirir, intermediar, transportar ou comercializar produto ou subproduto de origem animal ou vegetal produzido sobre área objeto de embargo. Parágrafo único. A aplicação do disposto neste artigo dependerá de prévia divulgação dos dados do imóvel rural, da área ou local embargado e do respectivo titular de que trata o § 1º do art. 18 e estará limitada à área onde efetivamente ocorreu o ilícito.",
        "fundamento_legal": "Art. 68, Decreto nº 7.315/2025",
        "natureza_multa": "FECHADA",
        "valor_minimo": 500,
        "valor_maximo": 500,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: NÃO SE APLICA | Atenuantes: NÃO SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": ""
      }
    ]
  },
  {
    "tipo_infracao": "FLORA",
    "infracoes": [
      {
        "resumo": "Destruir ou danificar florestas ou demais formas de vegetação natural ou utilizá-las com infringência das normas de proteção em área de APP",
        "descricao_completa": "Destruir ou danificar florestas ou demais formas de vegetação natural ou utilizá-las com infringência das normas de proteção em área considerada de preservação permanente, sem autorização do órgão competente, quando exigível, ou em desacordo com a obtida",
        "fundamento_legal": "Art. 56, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 5000,
        "valor_maximo": 50000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Realizar o corte seletivo de árvores",
        "descricao_completa": "Realizar o corte seletivo de árvores em área considerada de preservação permanente ou cuja espécie seja especialmente protegida ou considerada imune de corte, sem permissão da autoridade competente",
        "fundamento_legal": "Art. 57, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 5000,
        "valor_maximo": 20000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Extração de espécies minerais de florestas públicas",
        "descricao_completa": "Extrair de florestas de domínio público ou áreas de preservação permanente, sem prévia autorização, pedra, areia, cal ou qualquer espécie de minerais:",
        "fundamento_legal": "Art. 58, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 5000,
        "valor_maximo": 50000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Produção de carvão sem licença",
        "descricao_completa": "Transformar madeira oriunda de floresta ou demais formas de vegetação nativa em carvão, para fins industriais, energéticos ou para qualquer outra exploração, econômica ou não, sem licença ou em desacordo com as determinações legais",
        "fundamento_legal": "Art. 59, Decreto nº 7.315/2025",
        "natureza_multa": "FECHADA",
        "valor_minimo": 500,
        "valor_maximo": 500,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: NÃO SE APLICA | Atenuantes: NÃO SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": ""
      },
      {
        "resumo": "Receber ou adquirir  madeira serrada ou em tora, lenha, carvão ou outros produtos de origem vegetal, sem licença ou DOF",
        "descricao_completa": "Receber ou adquirir, para fins comerciais ou industriais, madeira serrada ou em tora, lenha, carvão ou outros produtos de origem vegetal, sem exigir a exibição de licença do vendedor, outorgada pela autoridade competente, e sem se munir da via que deverá acompanhar o produto até final beneficiamento",
        "fundamento_legal": "Art. 60, Decreto nº 7.315/2025",
        "natureza_multa": "FECHADA",
        "valor_minimo": 300,
        "valor_maximo": 300,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: NÃO SE APLICA | Atenuantes: NÃO SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": ""
      },
      {
        "resumo": "Vender, ter em depósito, transportar, ou guardar madeira, lenha, carvão ou outros produtos de origem vegetal sem licença",
        "descricao_completa": "Incorre nas mesmas multas quem vende, expõe à venda, tem em depósito, transporta ou guarda madeira, lenha, carvão ou outros produtos de origem vegetal, sem licença válida para todo o tempo da viagem ou do armazenamento, outorgada pela autoridade competente ou em desacordo com a obtida",
        "fundamento_legal": "Art. 60 § 1º, Decreto nº 7.315/2025",
        "natureza_multa": "FECHADA",
        "valor_minimo": 300,
        "valor_maximo": 300,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: NÃO SE APLICA | Atenuantes: NÃO SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": ""
      },
      {
        "resumo": "Impedir ou dificultar a regeneração natural de florestas ou demais formas de vegetação nativa",
        "descricao_completa": "Impedir ou dificultar a regeneração natural de florestas ou demais formas de vegetação nativa em unidades de conservação ou outras áreas especialmente protegidas, quando couber, área de preservação permanente, reserva legal ou demais locais cuja regeneração tenha sido indicada pela autoridade competente. Parágrafo único. O disposto no caput não se aplica para o uso permitido das áreas de preservação permanente.",
        "fundamento_legal": "Art. 61, Decreto nº 7.315/2025",
        "natureza_multa": "FECHADA",
        "valor_minimo": 5000,
        "valor_maximo": 5000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: NÃO SE APLICA | Atenuantes: NÃO SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": ""
      },
      {
        "resumo": "Destruir ou danificar florestas ou qualquer tipo de vegetação nativa, objeto de especial preservação",
        "descricao_completa": "Destruir ou danificar florestas ou qualquer tipo de vegetação nativa, objeto de especial preservação, não passíveis de autorização para exploração ou supressão",
        "fundamento_legal": "Art. 62, Decreto nº 7.315/2025",
        "natureza_multa": "FECHADA",
        "valor_minimo": 6000,
        "valor_maximo": 6000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: NÃO SE APLICA | Atenuantes: NÃO SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": ""
      },
      {
        "resumo": "Destruir ou danificar florestas ou qualquer tipo de vegetação nativa ou de espécies nativas plantadas, objeto de especial preservação",
        "descricao_completa": "Destruir ou danificar florestas ou qualquer tipo de vegetação nativa ou de espécies nativas plantadas, objeto de especial preservação, sem autorização ou licença da Autoridade competente",
        "fundamento_legal": "Art. 63, Decreto nº 7.315/2025",
        "natureza_multa": "FECHADA",
        "valor_minimo": 5000,
        "valor_maximo": 5000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: NÃO SE APLICA | Atenuantes: NÃO SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": ""
      },
      {
        "resumo": "Destruir, desmatar, danificar ou explorar floresta ou qualquer tipo de vegetação nativa ou de espécies nativas plantadas, em área de reserva legal ou servidão florestal, de domínio público ou privado",
        "descricao_completa": "Destruir, desmatar, danificar ou explorar floresta ou qualquer tipo de vegetação nativa ou de espécies nativas plantadas, em área de reserva legal ou servidão florestal, de domínio público ou privado, sem autorização prévia do órgão ambiental competente ou em desacordo com a concedida",
        "fundamento_legal": "Art. 64, Decreto nº 7.315/2025",
        "natureza_multa": "FECHADA",
        "valor_minimo": 5000,
        "valor_maximo": 5000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: NÃO SE APLICA | Atenuantes: NÃO SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": ""
      },
      {
        "resumo": "Executar manejo florestal sem autorização",
        "descricao_completa": "Executar manejo florestal sem autorização prévia do órgão ambiental competente, sem observar os requisitos técnicos estabelecidos em PMFS ou em desacordo com a autorização concedida",
        "fundamento_legal": "Art. 65, Decreto nº 7.315/2025",
        "natureza_multa": "FECHADA",
        "valor_minimo": 1000,
        "valor_maximo": 1000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: NÃO SE APLICA | Atenuantes: NÃO SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": ""
      },
      {
        "resumo": "Desmatamento",
        "descricao_completa": "Desmatar, a corte raso, florestas ou demais formações nativas, fora da reserva legal, sem autorização da autoridade competente",
        "fundamento_legal": "Art. 66, Decreto nº 7.315/2025",
        "natureza_multa": "FECHADA",
        "valor_minimo": 1000,
        "valor_maximo": 1000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: NÃO SE APLICA | Atenuantes: NÃO SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": ""
      },
      {
        "resumo": "Explorar ou danificar floresta ou qualquer tipo de vegetação nativa",
        "descricao_completa": "Explorar ou danificar floresta ou qualquer tipo de vegetação nativa ou de espécies nativas plantadas, localizada fora de área de reserva legal averbada, de domínio público ou privado, sem aprovação prévia do órgão ambiental competente ou em desacordo com a concedida. Parágrafo único. Incide nas mesmas penas quem deixa de cumprir a reposição florestal obrigatória.",
        "fundamento_legal": "Art. 67, Decreto nº 7.315/2025",
        "natureza_multa": "FECHADA",
        "valor_minimo": 300,
        "valor_maximo": 300,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: NÃO SE APLICA | Atenuantes: NÃO SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": ""
      },
      {
        "resumo": "Deixar de averbar a reserva legal",
        "descricao_completa": "Deixar de averbar a reserva legal",
        "fundamento_legal": "Art. 69, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 50,
        "valor_maximo": 500,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Destruir, danificar, lesar ou maltratar, por qualquer modo ou meio, plantas de ornamentação de logradouros públicos ou em propriedade privada alheia",
        "descricao_completa": "Destruir, danificar, lesar ou maltratar, por qualquer modo ou meio, plantas de ornamentação de logradouros públicos ou em propriedade privada alheia",
        "fundamento_legal": "Art. 70, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 100,
        "valor_maximo": 1000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Comercializar, portar ou utilizar motoserra",
        "descricao_completa": "Comercializar, portar ou utilizar em floresta ou demais formas de vegetação, motosserra sem licença ou registro da Autoridade competente",
        "fundamento_legal": "Art. 71, Decreto nº 7.315/2025",
        "natureza_multa": "FECHADA",
        "valor_minimo": 1000,
        "valor_maximo": 1000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: NÃO SE APLICA | Atenuantes: NÃO SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": ""
      },
      {
        "resumo": "Fazer uso de fogo",
        "descricao_completa": "Fazer uso de fogo em áreas agropastoris sem autorização do órgão competente ou em desacordo com a obtida. Parágrafo único. A pena será quintuplicada quando praticada de forma dolosa em período de emergência climática declarada por ato do Poder Público.",
        "fundamento_legal": "Art. 72, Decreto nº 7.315/2025",
        "natureza_multa": "FECHADA",
        "valor_minimo": 3000,
        "valor_maximo": 3000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: NÃO SE APLICA | Atenuantes: NÃO SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": ""
      },
      {
        "resumo": "Provocar incêndio em floresta",
        "descricao_completa": "Provocar incêndio em floresta ou qualquer forma de vegetação nativa",
        "fundamento_legal": "Art. 73, Decreto nº 7.315/2025",
        "natureza_multa": "FECHADA",
        "valor_minimo": 10000,
        "valor_maximo": 10000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: NÃO SE APLICA | Atenuantes: NÃO SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": ""
      },
      {
        "resumo": "Provocar incêndio em floresta cultivada",
        "descricao_completa": "Provocar incêndio em floresta cultivada",
        "fundamento_legal": "Art. 74, Decreto nº 7.315/2025",
        "natureza_multa": "FECHADA",
        "valor_minimo": 5000,
        "valor_maximo": 5000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: NÃO SE APLICA | Atenuantes: NÃO SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": ""
      },
      {
        "resumo": "Deixar de implementar, o responsável pelo imóvel rural, as ações de prevenção e de combate aos incêndios florestais em sua propriedade",
        "descricao_completa": "Deixar de implementar, o responsável pelo imóvel rural, as ações de prevenção e de combate aos incêndios florestais em sua propriedade de acordo com as normas estabelecidas pelo Comitê Nacional de Manejo Integrado do Fogo e pelos órgãos competentes do Sisnama",
        "fundamento_legal": "Art. 75, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 5000,
        "valor_maximo": 10000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Fabricar, vender, transportar ou soltar balões",
        "descricao_completa": "Fabricar, vender, transportar ou soltar balões que possam provocar incêndios nas florestas e demais formas de vegetação, em áreas urbanas ou qualquer tipo de assentamento humano",
        "fundamento_legal": "Art. 76, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 10000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      }
    ]
  },
  {
    "tipo_infracao": "MINERAÇÃO",
    "infracoes": [
      {
        "resumo": "Executar pesquisa, lavra ou extração de minerais sem a competente autorização, permissão, concessão ou licença da Autoridade competente ou em desacordo com a obtida",
        "descricao_completa": "Executar pesquisa, lavra ou extração de minerais sem a competente autorização, permissão, concessão ou licença da Autoridade competente ou em desacordo com a obtida. Parágrafo único. Incorre nas mesmas multas quem deixa de recuperar a área pesquisada ou explorada, nos termos da autorização, permissão, licença, concessão ou determinação do órgão ambiental competente.",
        "fundamento_legal": "Art. 80, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 5000,
        "valor_maximo": 50000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      }
    ]
  },
  {
    "tipo_infracao": "POLUIÇÃO E OUTRAS INFRAÇÕES",
    "infracoes": [
      {
        "resumo": "Causar poluição de qualquer natureza",
        "descricao_completa": "Causar poluição de qualquer natureza em níveis tais que resultem ou possam resultar em danos à saúde humana ou que provoquem a mortandade de animais ou a destruição significativa da biodiversidade. Parágrafo único. As multas e demais penalidades de que trata o caput serão aplicadas após laudo técnico ou Relatório Técnico Ambiental elaborado por técnico do órgão ambiental competente, identificando a dimensão do dano decorrente da infração e em conformidade com a gradação do impacto, sendo suficiente a potencialidade de dano à saúde humana para configuração da conduta infracional.",
        "fundamento_legal": "Art. 78, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 50000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "causar poluição tornando uma área, urbana ou rural, imprópria para ocupação humana",
        "descricao_completa": "causar poluição tornando uma área, urbana ou rural, imprópria para ocupação humana",
        "fundamento_legal": "Art. 79, I, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 50000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Causar poluição atmosférica",
        "descricao_completa": "causar poluição atmosférica que provoque a retirada, ainda que momentânea, dos habitantes das áreas afetadas ou que provoque, de forma recorrente, significativo desconforto respiratório ou olfativo devidamente atestado pelo agente autuante",
        "fundamento_legal": "Art. 79, II, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 50000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Causar poluição hídrica",
        "descricao_completa": "causar poluição hídrica que torne necessária a interrupção do abastecimento público de água de uma comunidade",
        "fundamento_legal": "Art. 79, III, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 50000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Causar poluição sonora",
        "descricao_completa": "causar poluição sonora, em decorrência de quaisquer atividades industriais, comerciais, sociais ou recreativas, inclusive as de propaganda política, acima dos padrões ambientais estabelecidos",
        "fundamento_legal": "Art. 79, IV, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 50000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Dificultar ou impedir o uso público das praias pelo lançamento de substâncias, efluentes, carreamento de materiais ou uso indevido dos recursos naturais",
        "descricao_completa": "dificultar ou impedir o uso público das praias pelo lançamento de substâncias, efluentes, carreamento de materiais ou uso indevido dos recursos naturais",
        "fundamento_legal": "Art. 79, V, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 50000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "lançar resíduos sólidos, líquidos ou gasosos ou detritos, óleos ou substâncias oleosas",
        "descricao_completa": "lançar resíduos sólidos, líquidos ou gasosos ou detritos, óleos ou substâncias oleosas em desacordo com as exigências estabelecidas em leis ou atos normativos",
        "fundamento_legal": "Art. 79, VI, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 50000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Deixar de dar destinação ambientalmente adequada a produtos, subprodutos, embalagens, resíduos ou substância",
        "descricao_completa": "deixar, aquele que tem obrigação, de dar destinação ambientalmente adequada a produtos, subprodutos, embalagens, resíduos ou substâncias quando assim determinar a lei ou ato normativo",
        "fundamento_legal": "Art. 79, VII, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 50000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Deixar de adotar medidas de precaução ou contenção em caso de risco ou de dano ambiental grave ou irreversível",
        "descricao_completa": "deixar de adotar, quando assim o exigir a autoridade competente, medidas de precaução ou contenção em caso de risco ou de dano ambiental grave ou irreversível",
        "fundamento_legal": "Art. 79, VIII, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 50000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Provocar pela emissão de efluentes ou carreamento de materiais o perecimento de espécimes da biodiversidade",
        "descricao_completa": "Provocar pela emissão de efluentes ou carreamento de materiais o perecimento de espécimes da biodiversidade",
        "fundamento_legal": "Art. 79, IX, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 50000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Lançar resíduos sólidos ou rejeitos",
        "descricao_completa": "lançar resíduos sólidos ou rejeitos em praias, no rio ou quaisquer recursos hídricos",
        "fundamento_legal": "Art. 79, X, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 50000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Lançar resíduos sólidos ou rejeitos in natura a céu aberto",
        "descricao_completa": "lançar resíduos sólidos ou rejeitos in natura a céu aberto, excetuados os resíduos de mineração",
        "fundamento_legal": "Art. 79, XI, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 50000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Depositar resíduos sólidos ou rejeitos a céu aberto ou em recipientes, instalações e equipamentos não licenciados para a atividade",
        "descricao_completa": "Depositar resíduos sólidos ou rejeitos a céu aberto ou em recipientes, instalações e equipamentos não licenciados para a atividade",
        "fundamento_legal": "Art. 79, XII, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 50000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Descumprir obrigação prevista no sistema de logística reversa",
        "descricao_completa": "descumprir obrigação prevista no sistema de logística reversa implantado nos termos da Política Nacional de Resíduos Sólidos, consoante as responsabilidades específicas estabelecidas para o referido sistema e em acordo setorial de alcance nacional",
        "fundamento_legal": "Art. 79, XIII, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 50000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Deixar de segregar resíduos sólidos",
        "descricao_completa": "deixar de segregar resíduos sólidos na forma estabelecida para a coleta seletiva, quando a referida coleta for instituída pelo titular do serviço público de limpeza urbana e manejo de resíduos sólidos",
        "fundamento_legal": "Art. 79, XIV, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 50000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Destinar resíduos sólidos urbanos à recuperação energética em desacordo com a Política Nacional de Resíduos Sólidos",
        "descricao_completa": "Destinar resíduos sólidos urbanos à recuperação energética em desacordo com a Política Nacional de Resíduos Sólidos",
        "fundamento_legal": "Art. 79, XV, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 50000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Deixar de manter atualizadas e disponíveis informações completas sobre a realização das ações do sistema de logística reversa",
        "descricao_completa": "deixar de manter atualizadas e disponíveis ao órgão municipal competente e a outras autoridades informações completas sobre a realização das ações do sistema de logística reversa sobre sua responsabilidade",
        "fundamento_legal": "Art. 79, XVI, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 50000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Não manter atualizadas e disponíveis informações completas sobre a implementação e a operacionalização do plano de gerenciamento de resíduos sólidos",
        "descricao_completa": "não manter atualizadas e disponíveis ao órgão ambiental competente informações completas sobre a implementação e a operacionalização do plano de gerenciamento de resíduos sólidos sob sua responsabilidade",
        "fundamento_legal": "Art. 79, XVII, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 50000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Deixar de atender às regras sobre registro, gerenciamento e informação de resíduos perigosos",
        "descricao_completa": "deixar de atender às regras sobre registro, gerenciamento e informação de resíduos perigosos",
        "fundamento_legal": "Art. 79, XVIII, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 50000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      }
    ]
  },
  {
    "tipo_infracao": "PRODUTOS/SUBSTÂNCIAS PERIGOSAS",
    "infracoes": [
      {
        "resumo": "Produzir, processar, embalar, importar, exportar, comercializar, fornecer, transportar, armazenar, guardar, ter em depósito ou usar produto ou substância tóxica, perigosa ou nociva à saúde humana ou ao meio ambiente",
        "descricao_completa": "Produzir, processar, embalar, importar, exportar, comercializar, fornecer, transportar, armazenar, guardar, ter em depósito ou usar produto ou substância tóxica, perigosa ou nociva à saúde humana ou ao meio ambiente, em desacordo com as exigências estabelecidas em leis ou em seus regulamentos. § 1º Incorre nas mesmas penas quem abandona os produtos ou substâncias referidas no caput, descarta de forma irregular ou os utiliza em desacordo com as normas de segurança",
        "fundamento_legal": "Art. 81, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 500,
        "valor_maximo": 2000000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      }
    ]
  },
  {
    "tipo_infracao": "VEÍCULOS - CONDUÇÃO EM DESACORDO",
    "infracoes": [
      {
        "resumo": "Conduzir, permitir ou autorizar a condução de veículo automotor em desacordo com os limites e exigências ambientais previstos na legislação",
        "descricao_completa": "Conduzir, permitir ou autorizar a condução de veículo automotor em desacordo com os limites e exigências ambientais previstos na legislação",
        "fundamento_legal": "Art. 84, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 1000,
        "valor_maximo": 10000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      },
      {
        "resumo": "Alterar ou promover a conversão de qualquer item em veículos ou motores novos ou usados que provoque alterações nos limites e exigências ambientais previstas na legislação",
        "descricao_completa": "Alterar ou promover a conversão de qualquer item em veículos ou motores novos ou usados que provoque alterações nos limites e exigências ambientais previstas na legislação",
        "fundamento_legal": "Art. 85, Decreto nº 7.315/2025",
        "natureza_multa": "ABERTA",
        "valor_minimo": 500,
        "valor_maximo": 10000,
        "valor_por_unidade": null,
        "unidade_de_medida": null,
        "criterios_aplicacao": "Regra do sistema; aplicar parâmetros e multiplicadores definidos na Etapa 3 conforme Decreto nº 7.315/2025.",
        "observacoes": "Agravantes: SE APLICA | Atenuantes: SE APLICA",
        "duplicidade": false,
        "tipos_relacionados": "",
        "valor_fixo": "-",
        "fixo": "-"
      }
    ]
  }
]

// Normalizar dados com tipo computado
export const infracoesData: InfracaoBloco[] = rawData.map((bloco) => ({
  ...bloco,
  infracoes: bloco.infracoes.map((inf) => ({
    ...inf,
    _categoria: bloco.tipo_infracao,
    _tipo_multa_computado: detectTipoMulta(inf),
  })),
}))
