import base64
import json

# Base64 completo extraído do HTML original
base64_data = 'W3sidGlwb19pbmZyYWNhbyI6IkFUSVZJREFERSBTRU0gTElDRU7Dh0EiLCJpbmZyYWNvZXMiOlt7InJlc3VtbyI6IkFUSVZJREFERSBTRU0gTElDRU7Dh0EvREVTQ1VNUFJJTUVOVE8gREUgQ09ORElDSU9OQU5URVMiLCJkZXNjcmljYW9fY29tcGxldGEiOiJDb25zdHJ1aXIsIHJlZm9ybWFyLCBhbXBsaWFyLCBpbnN0YWxhciBvdSBmYXplciBmdW5jaW9uYXIgZXN0YWJlbGVjaW1lbnRvcywgYXRpdmlkYWRlcywgb2JyYXMgb3Ugc2VydmnDp29zIHV0aWxpemFkb3JlcyBkZSByZWN1cnNvcyBhbWJpZW50YWlzLCBjb25zaWRlcmFkb3MgZWZldGl2YSBvdSBwb3RlbmNpYWxtZW50ZSBwb2x1aWRvcmVzLCBzZW0gbGljZW7Dp2Egb3UgYXV0b3JpemHDp8OjbyBkb3Mgw7NyZ8Ojb3MgYW1iaWVudGFpcyBjb21wZXRlbnRlcywgZW0gZGVzYWNvcmRvIGNvbSBhIGxpY2Vuw6dhIG9idGlkYSBvdSBjb250cmFyaWFuZG8gYXMgbm9ybWFzIGxlZ2FpcyBlIHJlZ3VsYW1lbnRvcyBwZXJ0aW5lbnRlcyIsImZ1bmRhbWVudG9fbGVnYWwiOiJBcnQuIDgyLCBEZWNyZXRvIG7CuiA3LjMxNS8yMDI1IiwibmF0dXJlemFfbXVsdGEiOiJBQkVSVEEiLCJ2YWxvcl9taW5pbW8iOjUwMC4wLCJ2YWxvcl9tYXhpbW8iOjEwMDAwMDAwLjAsInZhbG9yX3Bvcl91bmlkYWRlIjpudWxsLCJ1bmlkYWRlX2RlX21lZGlkYSI6bnVsbCwiY3JpdGVyaW9zX2FwbGljYWNhbyI6IlJlZ3JhIGRvIHNpc3RlbWE7IGFwbGljYXIgcGFyw6JtZXRyb3MgZSBtdWx0aXBsaWNhZG9yZXMgZGVmaW5pZG9zIG5hIEV0YXBhIDMgY29uZm9ybWUgRGVjcmV0byBuwrogNy4zMTUvMjAyNS4iLCJvYnNlcnZhY29lcyI6IkFncmF2YW50ZXM6IFNFIEFQTElDQSB8IEF0ZW51YW50ZXM6IFNFIEFQTElDQSIsImR1cGxpY2lkYWRlIjpmYWxzZSwidGlwb3NfcmVsYWNpb25hZG9zIjoiIiwidmFsb3JfZml4byI6Ii0iLCJmaXhvIjoiLSJ9LHsicmVzdW1vIjoiQ29uc3RydWlyLCByZWZvcm1hciwgYW1wbGlyYSwgaW5zdGFsYXIgb3UgZmF6ZXIgZnVuY2lvbmFyIGVzdGFiZWxlY2ltZW50bywgb2JyYSBvdSBzZXJ2acOnbyBzdWplaXRvIGEgbGljZW5jaWFtZW50byBhbWJpZW50YWwgbG9jYWxpemFkbyBlbSB1bmlkYWRlIGRlIGNvbnNlcnZhw6fDo28gb3UgZW0gc3VhIHpvbmEgZGUgYW1vcnRlY2ltZW50bywgb3UgZW0gw6FyZWFzIGRlIHByb3Rlw6fDo28gZGUgbWFuYW5jaWFpcyBsZWdhbG1lbnRlIGVzdGFiZWxlY2lkYXMsIHNlbSBhbnXDqm5jaWEgZG8gcmVzcGVjdGl2byDDs3Jnw6NvIGdlc3RvciIsImRlc2NyaWNhb19jb21wbGV0YSI6ImNvbnN0csOzaSwgcmVmb3JtYSwgYW1wbGlhLCBpbnN0YWxhIG91IGZheiBmdW5jaW9uYXIgZXN0YWJlbGVjaW1lbnRvLCBvYnJhIG91IHNlcnZpw6dvIHN1amVpdG8gYSBsaWNlbmNpYW1lbnRvIGFtYmllbnRhbCBsb2NhbGl6YWRvIGVtIHVuaWRhZGUgZGUgY29uc2VydmHDp8OjbyBvdSBlbSBzdWEgem9uYSBkZSBhbW9ydGVjaW1lbnRvLCBvdSBlbSDDoXJlYXMgZGUgcHJvdGXDp8OjbyBkZSBtYW5hbmNpYWlzIGxlZ2FsbWVudGUgZXN0YWJlbGVjaWRhcywgc2VtIGFudeVuY2lhIGRvIHJlc3BlY3Rpdm8gw7NyZ8OjbyBnZXN0b3IiLCJmdW5kYW1lbnRvX2xlZ2FsIjoiQXJ0LiA4MiwgRGVjcmV0byBuwrogNy4zMTUvMjAyNSIsIm5hdHVyZXphX211bHRhIjoiQUJFUlRBIiwidmFsb3JfbWluaW1vIjo1MDAuMCwidmFsb3JfbWF4aW1vIjoxMDAwMDAwMC4wLCJ2YWxvcl9wb3JfdW5pZGFkZSI6bnVsbCwidW5pZGFkZV9kZV9tZWRpZGEiOm51bGwsImNyaXRlcmlvc19hcGxpY2FjYW8iOiJSZWdyYSBkbyBzaXN0ZW1hOyBhcGxpY2FyIHBhcsOibWV0cm9zIGUgbXVsdGlwbGljYWRvcmVzIGRlZmluaWRvcyBuYSBFdGFwYSAzIGNvbmZvcm1lIERlY3JldG8gbsK6IDcuMzE1LzIwMjUuIiwib2JzZXJ2YWNvZXMiOiJBZ3JhdmFudGVzOiBTRSBBUExJQ0EgfCBBdGVudWFudGVzOiBTRSBBUExJQ0EiLCJkdXBsaWNpZGFkZSI6ZmFsc2UsInRpcG9zX3JlbGFjaW9uYWRvcyI6IiIsInZhbG9yX2ZpeG8iOiItIiwiZml4byI6Ii0ifV19XQ=='

# Decodifica o base64
decoded = base64.b64decode(base64_data).decode('utf-8')
data = json.loads(decoded)

# Salva em arquivo JSON
with open('public/infracoes-complete.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"✓ Extraídas {len(data)} categorias de infrações")
total_infracoes = sum(len(cat.get('infracoes', [])) for cat in data)
print(f"✓ Total de {total_infracoes} infrações individuais")
print(f"✓ Arquivo salvo em: public/infracoes-complete.json")
